# Generated by Django 5.0.6 on 2025-05-12 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothingitem",
            name="owner",
        ),
    ]
